### ISSUE TITLE
Destroy object causes Editor stop.

### ISSUE THREAD

**Issue by Alestate** [tentone/nunuStudio#268] opened 2019-02-24 16:15 UTC
Destroy object causes Editor stop.

When the script calls an obj.destroy() the Editor shows a error message and game stops.this error did not occur in the previous version.
 
Console message:
nunuStudio: Error while running program. TypeError: Cannot read property 'traverse' of undefined
    at Container.traverse (nunu.editor.min.js:619)
    at Scene.update (nunu.editor.min.js:2714)
    at Program.update (nunu.editor.min.js:2702)
    at RunProject.update (nunu.editor.min.js:5573)
    at b (nunu.editor.min.js:5432

##### Version
0.9.6 Build 201902221518
three.js R102dev

##### Platform
 - Chrome 72.0.3626.119
 - Windows 10

**Comment by tentone** [comment] 2019-02-26 16:06
Hi

THanks a lot i will take a look at this problem, ASAP it was caused by a recent code change.

Thanks a lot.

Cheers

**Comment by tentone** [comment] 2019-03-04 21:27
Should be fixed now (web version). Thanks a lot!

**Closed by tentone** 2019-03-04 21:27 UTC
Labels: Bug
