### ISSUE TITLE
How is it that when I hold down the mouse and drag left it orbit anti-clockwise ? The same for moving mouse up and down, is basic navigation completely broken ?

### ISSUE THREAD

**Issue by BracerJack** [tentone/nunuStudio#408] opened 2020-06-19 21:31 UTC
20 June 2020
How is it that when I hold down the mouse and drag left it orbit anti-clockwise ?
The same for moving mouse up and down, is basic navigation completely broken ?

If you were to go to your main page: https://nunustudio.org/index.html
Click and dragging actually orbit the CORRECT WAY but it is completely reversed inside nunuStudio.

**Comment by tentone** [comment] 2020-06-20 08:41
Hello

Please check your settings on the editor to ensure that inverted mouse is not enabled for the editor navigation.

Otherwise this might be some sort of bug and i will need some additional details (browser, type of mouse, etc).

![zxczc](https://user-images.githubusercontent.com/9158354/85197602-0a153c80-b2da-11ea-8453-f54bb3b81769.PNG)

Thanks a lot!

**Comment by BracerJack** [comment] 2020-06-20 11:31
I literally just open the program, did not even go to the preference whatsoever.
Thank you for your quick respond, I currently deleted the program until this basic issue is fix.

**Comment by tentone** [comment] 2020-06-22 21:38
Thanks a lot. Since i cannot reproduce this issue i will close it.

**Closed by tentone** 2020-06-22 21:38 UTC
Labels: Question

**Comment by BracerJack** [comment] 2020-06-23 19:43
I re-install a fresh copy of windows and tried again.
Same issue.

**Comment by tentone** [comment] 2020-06-23 22:14
Reinstalling of course will not solve the issue.

Im open to try and solve it but i need some information, since this is not something that im able to reproduce and has never been reported before. Operative system? Version of the application? Any particularity in your mouse input?

**Comment by BracerJack** [comment] 2020-06-23 23:01
I think the viewport is updown inverted ?
I am currently too busy to make a video and talk about it in my channel, I will update you when I get around to it.

THANK YOU anyway, you are really responsive....it gives me confidence about this engine.
Thank you, thank you for being so responsible, your respond alone is worth applauding.

**Comment by 01miaom** [comment] 2022-03-18 23:17
> Reinstalling of course will not solve the issue.
> 
> Im open to try and solve it but i need some information, since this is not something that im able to reproduce and has never been reported before. Operative system? Version of the application? Any particularity in your mouse input?

I meet the same problem, when using orbit as camera navigation mode, the movement was reversed. Also the invert vertical in the settings doesn't seem to work. In MacOS, chrome 99.0.  (In threejs editor, the orientation is normal.)
