### ISSUE TITLE
Editor on the web doesnt work

### ISSUE THREAD

**Issue by setpixel** [tentone/nunuStudio#304] opened 2019-07-09 00:47 UTC
https://nunustudio.org/editor/index.html

from console: 

```nunu.editor.min.js:4376 Uncaught Error: THREE.VRMLLoader: External library chevrotain.min.js required.
    at nunu.editor.min.js:4376
    at nunu.editor.min.js:4413
nunu.editor.min.js:8123 Uncaught TypeError: this.loadDefault is not a function
    at new Settings (nunu.editor.min.js:8123)
    at Function.Editor.initialize (nunu.editor.min.js:2730)
    at onload (index.html:1)
nunu.editor.min.js:2740 Uncaught TypeError: Cannot read property 'updateInterface' of undefined
    at Function.Editor.resize (nunu.editor.min.js:2740)
    at onresize (index.html:1)```

**Comment by tentone** [comment] 2019-07-09 07:43
Hi.

Thanks a lot for reporting it was caused by a missing library in the build.

Should be fixed now.

Thanks a lot!.

Cheers

**Closed by tentone** 2019-07-09 07:43 UTC
