### ISSUE TITLE
Error loading file TypeError: First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by faviouz** [tentone/nunuStudio#89] opened 2017-09-12 15:32 UTC
I am getting an odd error upon loading a project which I was not getting before

![image](https://user-images.githubusercontent.com/180382/30334561-e2785ce0-97d7-11e7-963b-8e051690be8b.png)

![image](https://user-images.githubusercontent.com/180382/30334538-cbd8a40e-97d7-11e7-92c5-31d2d6d4cbcd.png)

**Comment by tentone** [comment] 2017-09-12 15:59
Hi

This was caused by new code to move away from base64 binary data serialization.

Yesterday i reverted the changes that caused this problem. Files created with the code that caused this cant be loaded right now, but im already working on it.

Thanks a lot for reporting the problem.

Cumps

**Comment by tentone** [comment] 2017-09-12 21:46
Hi @faviouz 

Should be fixed now, please let me know when you test it.

Thanks a lot.

Cumps

**Closed by tentone** 2017-09-12 21:46 UTC
Labels: Bug

**Comment by faviouz** [comment] 2017-09-12 22:06
Yep, all good now! Thanks :)

**Comment by tentone** [comment] 2017-09-12 22:07
Awesome this should save about 35% file for resources stored in nsp files.
